### ISSUE TITLE
Process: Clarification for what's meant by 'active'

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/rfcs#2]
I don't think the README sufficiently clarifies what's meant by 'active'.

Does 'active' just mean 'open'?

Perhaps part of the confusion comes from the line that says someone can write an implementation whilst the RFC is active - which seems like a potential waste of time if the RFC was to then get rejected.

**Comment by ntwb** [comment]
An RFC becomes `active` once the proposal pull request has been merged.

So, yes, some tweaks to that verbiage would be helpful (most of this repo is via cut and paste from React/Yarn RFC repos) with some minor edits

**Comment by ntwb** [comment]
Closing this and archiving this repository.
