### ISSUE TITLE
Suggestion: notify stakeholders when an RFC goes into final comment

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/rfcs#4]
Should there be a formalized process to notify stakeholders about RFCs ?

I would like to suggest notifications should go out when an RFC goes into the final comment phase (as before that it may still be too much in flux to warrant time for all but the most invested stakeholders).

I think that a notification about an RFC going into the final comment phase should be posted in:
* The #core-coding-standards Slack channel
* The #core-committers Slack channel
* Maybe a blogpost on make.wordpress.org ?
* ... ? (suggestions welcome)

If we could automate this based on the label: all the better!

I'm suggesting this as I think RFCs should reach a wider public than just those who are actively involved with creating and maintaining the coding standards and I don't think we currently reach them sufficiently.

For now, I've taken the liberty to post in both the above mentioned Slack channels about the Type Declaration RFC #3 going into final comments.

**Comment by ntwb** [comment]
Thanks @jrfnl, I like the sounds of this 👍 

One of the objectives of this repo was to *not* be a place for lots of people to _drive-by_ adding thumbs up, down, or +1's in the issue and pull request comments. When an RFC is first created the initial stakeholders should be included by way of mentioning/pinging their GitHub username, e.g. @jrfnl 

As such I think your proposal here happily finds that intermediate ground by avoiding mass communicating the RFC too early in the process 👍 

> The #core-coding-standards Slack channel
> The #core-committers Slack channel

Yes & Yes, and thanks for dropping the pings in Salck ❤️ 

> Maybe a blogpost on make.wordpress.org ?

I think so, though in reading the last 4 items from [the process](https://github.com/WordPress-Coding-Standards/rfcs#what-the-process-is) as it currently stands I'm trying to envisage how, be it better or worse communicating that on make/core would affect an RFC by having widespread review comment. I'm thinking the below _process_ might require a few tweaks and instead we make the make/core post after that _"7 calendar days"_ "final comment period".

> • RFCs that are candidates for inclusion in the WordPress Coding Standards will enter a "final comment period" lasting 7 calendar days. The beginning of this period will be signaled with a comment and tag on the RFCs pull request.
> • An RFC can be modified based upon feedback from the team and community. Significant modifications may trigger a new final comment period.
> • An RFC may be rejected by the team after public discussion has settled and comments have been made summarizing the rationale for rejection. A member of the team should then close the RFCs associated pull request.
> • An RFC may be accepted at the close of its final comment period. A team member will merge the RFCs associated pull request, at which point the RFC will become 'active'.

Lastly, yes, we should as you've stated @jrfnl be aiming to reach a wider audience, the coding standards teams and projects have started to integrate closer with the core team than ever before. With Tide coming along all the more reason to extend public reach 👍

**Comment by jrfnl** [comment]
>  I'm thinking the below process might require a few tweaks and instead we make the make/core post after that "7 calendar days" "final comment period".

In that case, a new step would need to be introduced after the final comment period and before merging as otherwise, an RFC would become "active" too early and would need to be withdrawn again if public sentiment would go counter.

If such an additional step is introduced, maybe it should be a form of "voting" (after the final comment period) ?
In that case, maybe we should even consider a voting board with representatives of both Core as well as the community ?

**Comment by ntwb** [comment]
Closing this and archiving this repository.
