### ISSUE TITLE
Process: clarify what is meant by "implement"

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/rfcs#6]
This is a follow-up on a discussion started in PR #5.
 
The words "implement" and "implementation" are used a number of times in the [README](https://github.com/WordPress-Coding-Standards/rfcs/blob/087159f845eabd5bca4c3445c0be57f3d265b94e/README.md) when talking about the process.

In my opinion that verbiage is unclear and causing confusion.

Before sending in a PR to change it, I'd like to gather some more opinions on people's interpretation of it.

My personal interpretation of what "implement" can mean in the context of accepted/active WPCS RFCs is:
* Add existing (upstream) sniffs and/or write new sniffs for WPCS to allow for automated checking and - if possible - fixing of the code formatting - if any - as prescribed in the RFC.
    If Core should follow, the sniffs will go into the `Core` ruleset, otherwise `Extra`.
* If the RFC proscribes that Core should follow the standard, add a short version of the RFC to the (PHP?) Coding Standards part of the make.wordpress.org/core handbook.
* If Core should comply:
     - Test if Core contains any violations. If not, no other action is needed.
     - If violations are found and (partial) automated fixing is possible, create a patch using `phpcbf` to fix the relevant code in Core and submit it via Trac.
    - If fully automated fixing is not possible, open a Trac issue about it listing the (remaining) violations and accept patches for Core fixing the various violations.
* For the wider WP community: 
    - Each project has the freedom to decide whether they want to comply with the new standard. 
        Compliance is highly recommended for projects which are seen as examples to the community - such as, for instance, the `_s` theme - and for projects which have the ambition to at some point in the future be accepted into Core.
    - Test if projects contain violations and if so, (submit PRs to) fix them.

I'm probably still missing some possible interpretations, so additions to this list are welcome!

**Comment by GaryJones** [comment]
I'd put your second step first - getting it into the Handbook is (for my understanding) the primary purpose of the RFC, and that's why I suggest having a section in the RFC as a starting point for the Handbook content, as per #4.

Once it's there, _then_ the WPCS folks can implement the PHPCS-based solutions, _then_ Core or plugin/themes can be updated to fix violations.

**Comment by jrfnl** [comment]
> I'd put your second step first

*grin* When writing the text, I actually originally had it as the second bullet.
The reason why I changed it to be the first:
1. These bullets are unordered, so do not necessarily imply an order to the steps. These actions could be executed simultaneously (except for the auto-fixing).
2. And more importantly: not all RFCs will apply to Core, so if an RFC is accepted for use by the wider WP community, but should not be implemented - at this time - by Core, the sniffs should still be added to WPCS (in `Extra`).
    If something which initially did not apply to Core, at a later stage, gets added to the handbook, the sniff(s) can be moved from `Extra` to `Core`.

**Comment by GaryJones** [comment]
I don't see that being the split between _Core_ and _Extra_. No time now to go into detail though.

**Comment by ntwb** [comment]
Closing this and archiving this repository.
