### ISSUE TITLE
Process: Clarify what's meant by "the team"

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/rfcs#9]
I really like the idea of an RFC process for coding standards (I'd like to see a proper RFC process for core features and changes too, but that's a whole other ball game).

That said, RFCs are only effective if they are well governed. To that end, who is "the team" mentioned in [What the process is](https://github.com/WordPress-Coding-Standards/rfcs/blob/master/README.md#what-the-process-is)?

> Eventually, the team will decide whether the RFC is a candidate for inclusion in the WordPress Coding Standards.

It might be that the team hasn't been determined yet, which is fine, but it should be.

Discussion welcome.

**Comment by jrfnl** [comment]
Related: https://github.com/WordPress-Coding-Standards/rfcs/issues/4#issuecomment-371466969

**Comment by GaryJones** [comment]
This has been the problem I've gone against for the last few years - there is no-one who can effectively own this.

- Some, but not all Core Committers have an interest in this, and those that do often have very opposing views. See the recent views about multi-line function calls: @azaozz is fairly against them, but @ocean90 was happy to skip the RFC process and get a sentence or two straight into the Handbook. 
- The WPCS committers/admin typically agree with each other, but that's of little use if a proposal would never have the potential to get into Core.

One of the things @ntwb is trying to aim for, is to have `WPCS` as it's own team (i.e. at the level of other teams on make.wordpress.org/) - and whatever structure that would take (i.e. @jrfnl and @pento lead, and the rest of us regular participants as team members), IMO would form the basis of "the team" per this RFC context.

**Comment by azaozz** [comment]
> See the recent views about multi-line function calls: @azaozz is fairly against them, but @ocean90...

Correction! :)
- I'm very much against keeping a buggy rule in the parser that enforces inline arrays in function calls to be multi-line. This was never intended and is a bug that needs fixing.

- I'm also fairly against single parameters in function calls being on multiple lines. They are just harder to read, especially when there are other parameters.

- I also think that the standards need to define multi-line function calls better. 

As far as I see @ocean90 shares the same views. Also, the RFC process is good when proposing major new changes but IMHO shouldn't apply when fixing bugs :)

**Comment by ntwb** [comment]
Thanks for opening the issue John, you are correct, basically "the team" hasn't been decided yet...

The purpose of this repo is not to have coding standards voted in by popular vote, if someone has an idea to improve the coding standards then submitting a proposal here to discuss it with "the team".

As to who might be on "the team" it would vary depending on the request, for example:
• CSS - @helen, @peterwilsoncc
• SCSS - @helen, @peterwilsoncc
• PHP - @azaozz, @jorbin @johnbillion, the WPCS team
• JavaScript - @adamsilverstein, @azaozz
• React - @aduth, the Gutenberg team
• Markdown - The Docs & Meta team
(This is a pretty subjective list, solely based on whom comes immediately to mind for each language)

Again, it would vary dependant on each proposal and where the proposed changes are seeking to be implemented be it Core, Meta, the bb's, GlotPress, Gutenberg, or externally where the community is seeking modern PHP standards not yet adopted by _core_. 

I included a "Lead Developer" in most of the languages listed above, depending on the proposal a _lead_ may be required early in the proposal process for a preliminary nod of approval to avoid having wasting contributors time on a proposal that would never see the light of day. I'd also like to see a _lead_ sign-off on the final proposal even if their only involvement in the proposal was reviewing and publishing the final P2 post on make/core.

The size of the team reviewing a proposal only requires a couple of people who are knowledgeable in the subject being discussed, the process has not been implemented to add bureaucracy for the sake of it, if the proposal is a good idea let us just get it implemented.

Once a proposal has been accepted "the team" who implements the proposal would not necessarily be "the team" that originally discussed and accepted the proposal, there would be documentation and code examples to be written, _build tooling_ to be updated with _new/updates_ to the languages _rules/sniffs_.

Lastly as an aside for some further context, with the coding standards updates that have already landed in core, to those still to come, to the Tide project, each of the PHP, CSS, SCSS, JS, and Accessibility coding standards require articulate documentation and to that end the plan is to have these coding standards centrally documented at https://developer.wordpress.org/coding-standards with the documentation synch'd from the https://github.com/WordPress-Coding-Standards/docs repo similar to how WP-CLI & WP-API are kept in sync via GitHub repos to https://developer.wordpress.org/

**Comment by ntwb** [comment]
> Also, the RFC process is good when proposing major new changes but IMHO shouldn't apply when fixing bugs :)

Agreed 100% if something is broken fix it. As I noted in my previous comment this RFC process is not here to add bureaucracy for the sake of it.

----

The one part of the process that will change though is that handbook changes will be required to be made to the https://github.com/WordPress-Coding-Standards/docs repo as the current handbook pages will go away once https://developer.wordpress.org/coding-standards is up and running

**Comment by ntwb** [comment]
Closing this and archiving this repository.
